[tool.poetry]
name = "apainvoice"
version = "0.1.0"
description = ""
authors = ["Shahvir Buhariwalla <shahvirb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
fastui = "^0.6.0"
fastapi = "^0.112.0"
uvicorn = "^0.30.5"

[tool.poetry.scripts]
webserver = "uvicorn webapp:app --reload"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
